server:
  port: 8081
  shutdown: graceful #优雅停机
spring:
  main:
    allow-circular-references: false
  application:
    name: paycore
  lifecycle:
    timeout-per-shutdown-phase: 30s #t缓冲时间配置，默认30s
  # 多数据源配置
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为 master
      strict: true # 设置严格模式，当数据源找不到时，是否抛出异常，默认为false不抛出
      datasource:
        master: # 主库
          url: jdbc:mysql://192.168.197.100:3306/paycore?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useServerPrepStmts=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&nullCatalogMeansCurrent=true
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave: # 从库
          url: jdbc:mysql://192.168.197.100:3306/paycore?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useServerPrepStmts=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&nullCatalogMeansCurrent=true
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 1abb83bd-2aa4-47ad-8953-001da367723d
  #启动虚拟线程
  threads:
    virtual:
      enabled: true

## MyBatis-plus配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
dubbo:
  application:
    name: ${spring.application.name}
  provider: &dubbocofig
    filter: traceId
    check: false
    retries: 0
    timeout: 10000
  consumer:
    <<: *dubbocofig
    #filter: traceId
    #check: false
    #retries: 0
    #timeout: 10000
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    basePackages: com.xiacong.provider

log:
  level: debug
  path: /home/moe/logs
