package com.xiacong.util;

import lombok.Data;

import java.math.BigDecimal;
import java.util.List;

@Data
public class HomeStayRes {

        private String ticketList;
        private Integer ticket_id;
        private Integer id;
        private Integer domainid;
        private String letway;
        private String same_housing_resources_no;
        private String housing_resources_type;
        private String housing_resources_place;
        private String housing_resources_address;
        private String explain;
        private String village_name;
        private String building_door;
        private String village_x;
        private String village_y;
        private String spot_name;
        private String housetype;
        private String housearea;
        private String server;
        private String bedtype;
        private String bathroomtype;
        private String housing_resources_view;
        private String room_name;
        private String room_smallname;
        private String housing_resources_characteristic;
        private String traffic_location;
        private String area_Integerroduce;
        private String start_time;
        private String end_time;
        private String sex;
        private String clean_way;
        private String requirement;
        private String price;
        private String iscleanmoney;
        private String cleanmoney;
        private String people_no;
        private String isaddpeople;
        private String addmoney;
        private String isgetmoney;
        private String whereday;
        private String percentage;
        private String mindays;
        private String maxdays;
        private String starttime2;
        private String endtime2;
        private String exittime;
        private String updatebed;
        private String giveteeth;
        private String givetowel;
        private String smoking;
        private String partying;
        private String cooking;
        private String dog;
        private String children;
        private String kids;
        private String oldpeople;
        private String photo;
        private String bathroom;
        private String wc;
        private String saloon;
        private String kitchen;
        private String study;
        private String balcony;
        private String cover;
        private String bathroom_pic;
        private String saloon_pic;
        private String kitchen_pic;
        private String wc_pic;
        private String other_pic;
        private String status;
        private Integer did;
        private String domain_name;
        private String address;
        private String iphone;
        private String ticketname;
        private String contact;
        private String sheng;
        private String shi;
        private String qu;
        private String marketprice;
        private String sellingprice;
        private String settlementprice;
        private Integer num;
        private String list;
        private BigDecimal minprice;
        private BigDecimal maxprice;
        private Double distance;
        private String typename;
        private Integer shoucangstatus;
        private List<Selltickets> selltickets;
}
