management:
  port: 8080
  security:
    enabled: false
  endpoints:
    web:
      #cros调用配置
      #      cors:
      #        allowed-origins: https://www.choupangxia.com
      #        allowed-methods: GET,POST
      exposure:
        include: '*'
  #基础路径修改，默认为 /actuator
  #      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
